AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example SAM template for a Lambda-based chat backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      Environment:
        Variables:
          BLOCKETHER_LLM_API_BASE_URL: !Sub '${BlocketherLLMBaseUrl}'
          BLOCKETHER_LLM_API_KEY: !Sub '${BlocketherLLMAPIKey}'
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          AWS_LWA_ASYNC_INIT: "true"
          AWS_LWA_ENABLE_COMPRESSION: "true"
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM

Parameters:
  BlocketherLLMBaseUrl:
    Type: String
    Default: ""
    Description: Base URL for the LLM API
  BlocketherLLMAPIKey:
    Type: String
    Default: ""
    NoEcho: true
    Description: API key for the LLM


Outputs:
  FastAPIFunctionUrl:
    Description: "Function URL for FastAPI function"
    Value: !GetAtt FastAPIFunctionUrl.FunctionUrl
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn